name: bullseye
description: ML-like functional language frontend for Dart Kernel IR.
version: 0.0.0
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  analyzer: ^0.33.0
  kernel: 0.3.6
  source_span: ^1.0.0
  string_scanner: ^1.0.0